version: '1'

services:
  vm-rent-api:
    container_name: vm-rent-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5000
    ports:
      - 5000:5000
      - 5001:5001
    networks:
      - demo-cqrs
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD=postgres
    ports:
    - 5432:5432
    networks:
      - demo-cqrs

networks:
  demo-cqrs:
    driver: bridge
    
    