version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - rodb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5000
    ports:
      - 5000:5000
      - 5001:5001
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=vm_rent
      - POSTGRES_USER=vm_rent
      - POSTGRES_PASSWORD=vm_rent
    expose:
      - 5432
  rodb:
    image: mongo:latest
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    expose: 
      - 27017
    
    
    