// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserService.Infrastructure;

namespace UserService.Infrastructure.Migrations
{
    [DbContext(typeof(UserServiceContext))]
    [Migration("20200617141704_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("UserService.Domain.Models.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<string>("EmailAddress")
                        .HasColumnName("email_address")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnName("first_name")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnName("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnName("last_name")
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .HasColumnName("login")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnName("password")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("user_id_pkey");

                    b.ToTable("user","public");
                });

            modelBuilder.Entity("UserService.Domain.Models.UserAggregate.User", b =>
                {
                    b.OwnsMany("UserService.Domain.Models.UserAggregate.Role", "Roles", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnName("user_id")
                                .HasColumnType("uuid");

                            b1.Property<string>("RoleName")
                                .HasColumnName("name")
                                .HasColumnType("text");

                            b1.HasKey("UserId", "RoleName");

                            b1.ToTable("user_role","public");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("user_user_id_fkey");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
